import type { Locale } from "@/i18n/config";
import type { Vehicle } from "@/data/types";

/**
 * Image strategy
 * - Files live in /public/images/cars/<slug>/ as 1.svg, 2.svg, 3.svg (demo placeholders, generated by `npm run gen:images`).
 * - To use real photography: drop 1.jpg / 2.jpg / 3.jpg (or .webp/.avif) in the same folder and change IMAGE_EXT below
 *   (or set per-vehicle `images` later). next/image then optimises them automatically.
 * - Social share images: /images/cars/<slug>/og.png (1200x630).
 */
export const IMAGE_EXT = "svg";
export const IMAGE_COUNT = 3;

export interface VehicleImage {
  src: string;
  alt: string;
  isPlaceholder: boolean;
}

const altTemplates: Record<Locale, (name: string, n: number) => string> = {
  en: (name, n) => `${name} available for rental in Dubai – view ${n}`,
  ar: (name, n) => `${name} متاحة للإيجار في دبي – صورة ${n}`,
  ru: (name, n) => `${name} в аренду в Дубае – фото ${n}`,
};

export function vehicleImages(v: Vehicle, locale: Locale): VehicleImage[] {
  return Array.from({ length: IMAGE_COUNT }, (_, i) => ({
    src: `/images/cars/${v.slug}/${i + 1}.${IMAGE_EXT}`,
    alt: altTemplates[locale](v.name, i + 1),
    isPlaceholder: IMAGE_EXT === "svg",
  }));
}

export const vehicleCover = (v: Vehicle, locale: Locale) => vehicleImages(v, locale)[0];
export const vehicleOgImage = (v: Vehicle) => `/images/cars/${v.slug}/og.png`;
export const DEFAULT_OG_IMAGE = "/images/og-default.png";
